name: unit test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Run Tests
      run: |
        python -m unittest tests/test_input_bill_number.py
        python -m unittest tests/test_bill.py
        python -m unittest tests/test_bet_type.py
        python -m unittest tests/test_city.py
        python -m unittest tests/test_printer.py
